version: 2.0
jobs:
  test-ready-branches:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Checkout master and merge with current branch step
          command: |
            git checkout origin/master
            git merge ${CIRCLE_BRANCH}
      - run:
          name: Installing requirements step
          command: pip install --user -r requirements.txt
      - run:
          name: Testing step
          command: python tests.py
      - store_test_results:
          path: test-reports
      - run:
          name: Push to origin master step
          command: git push origin master
  build-deploy-staging:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker staging image step
          command: docker build -t $DOCKER_USER/ca-project:staging .
      - run:
          name: Push Docker staging image step
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKER_USER/ca-project:staging
      - add_ssh_keys:
          fingerprints:
            - "76:b8:d8:04:1a:0d:65:ba:e7:c9:cc:3c:27:e0:9a:99"
      - run:
          name: Deploy to staging step
          command: |
            chmod +x deploy.sh
            chmod +x ips.sh
            ./deploy.sh staging
      - persist_to_workspace:
          root: .
          paths:
            - .
  stress-test-staging:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "76:b8:d8:04:1a:0d:65:ba:e7:c9:cc:3c:27:e0:9a:99"
      - run:
          name: Stress test staging step
          command: ssh ubuntu@`./ips.sh staging` siege http://localhost:80
  build-deploy-prod:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build Docker prod image step
          command: docker build -t $DOCKER_USER/ca-project:prod .
      - run:
          name: Push Docker prod image step
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKER_USER/ca-project:prod
      - add_ssh_keys:
          fingerprints:
            - "76:b8:d8:04:1a:0d:65:ba:e7:c9:cc:3c:27:e0:9a:99"
      - run:
          name: Deploy to prod step
          command: |
            chmod +x deploy.sh
            chmod +x ips.sh
            ./deploy.sh prod

  package-artifacts:
    machine: true
    steps:
      - attach_workspace:
          at: project/
      - run:
          name: Install zip tool
          command: sudo apt install zip -y
      - run:
          name: Change directory to parent
          command: cd ..
      - run:
          name: List directory
          command: ls
      - run:
          name: Zip project folder
          command: zip artifact.zip project
      - store-artifacts:
          path: ./artifact.zip
          destination: artifact-file

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test-ready-branches:
          filters:
            branches:
              only:
                - /ready/.*/
      - build-deploy-staging:
          filters:
            branches:
              only: master
      - stress-test-staging:
          requires:
            - build-deploy-staging
          filters:
            branches:
              only: master
      - build-deploy-prod:
          requires:
            - stress-test-staging
          filters:
            branches:
              only: master
      - package-artifacts:
          requires:
            - stress-test-staging
          filters:
            branches:
              only: master
