version: 2.0
jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Testing step
          command: |
            pip install --user -r requirements.txt
            python tests.py
      - persist_to_workspace:
          root: .
          paths:
            - .
  build-deploy-staging:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build Docker and push to staging step
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t $DOCKER_USER/ca-project:staging .
            docker push $DOCKER_USER/ca-project:staging
      - add_ssh_keys:
          fingerprints:
            - "76:b8:d8:04:1a:0d:65:ba:e7:c9:cc:3c:27:e0:9a:99"
      - run:
          name: Change permissions for deploy.sh
          command: chmod +x deploy.sh
      - run:
          name: List files
          command: ls -l
      - run:
          name: Deploy to staging step
          command: ./deploy.sh staging
workflows:
  version: 2
  test-build-deploy-staging:
    jobs:
      - test
      - build-deploy-staging:
          requires:
            - test
