version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Installing requirements step
          command: pip install --user -r requirements.txt
      - run:
          name: Testing step
          command: python tests.py
      - store_test_results:
          path: test-reports
      - persist_to_workspace:
          root: .
          paths:
            - .
  build-deploy-staging:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build Docker staging image step
          command: docker build -t $DOCKER_USER/ca-project:staging .
      - run:
          name: Push Docker staging image step
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKER_USER/ca-project:staging
      - add_ssh_keys:
          fingerprints:
            - "76:b8:d8:04:1a:0d:65:ba:e7:c9:cc:3c:27:e0:9a:99"
      - run:
          name: Deploy to staging step
          command: |
            chmod +x deploy.sh
            ./deploy.sh staging
orbs:
  pylint: qventus/python-lint@volatile
workflows:
  version: 2.1
  test-build-deploy:
    jobs:
      - test
      - pylint/lint
      - build-deploy-staging:
          requires:
            - test
          filters:
            branches:
              only: master
